### ISSUE TITLE
Сервер падает на авторизации после долгого простоя

### ISSUE THREAD

**Issue by nxt007** [GreenTeamSpbStu/SharedAccessList#28]
Лог сервера:

Fri May 08 16:07:58 EDT 2015     Handling query: /auth.api?mail=test@rambler.ru&passwd=123
May 08, 2015 4:07:58 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
WARN: SQL Error: 0, SQLState: 08003
May 08, 2015 4:07:58 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
ERROR: No operations allowed after connection closed.
org.hibernate.TransactionException: Transaction not successfully started
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.rollback(AbstractTransactionImpl.java:202)
        at server.core.HttpApiMehodImpl.prepareAnswer(HttpApiMehodImpl.java:70)
        at server.core.HttpApiMehodImpl.access$000(HttpApiMehodImpl.java:14)
        at server.core.HttpApiMehodImpl$1.handle(HttpApiMehodImpl.java:46)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:645)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by suhininalex** [comment]
После потери соединения с БД сервер тратится. Пока не понятно, можно ли это легко исправить

**Comment by suhininalex** [comment]
Двойной роллбэк прятал настоящую ошибку. Исправлено.

**Comment by suhininalex** [comment]
Вероятно новая ошибка будет говорить о проблемах соединения.
